workflows:
  ios-debug-build:
    name: iOS GreetDemoApp (No Signing)
    environment:
      vars:
        XCODE_WORKSPACE: "GreetDemoApp.xcworkspace"
        XCODE_SCHEME: "GreetDemoApp"
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build for simulator
        script: |
          cd ios
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 15'
          cd ..
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
      
