workflows:
  ios-debug-build:
    name: iOS GreetDemoApp (Simulator, No Signing)
    environment:
      vars:
        XCODE_WORKSPACE: "GreetDemoApp.xcworkspace"
        XCODE_SCHEME: "GreetDemoApp"
        DERIVED_DATA_PATH: "build"
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build for Simulator
        script: |
          cd ios
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath "$DERIVED_DATA_PATH"
          cd ..
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/GreetDemoApp.app
