workflows:
  ios-debug-simulator:
    name: iOS Simulator Build (no signing)
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "GreetDemoApp.xcworkspace"
        XCODE_SCHEME: "GreetDemoApp"
        DERIVED_DATA_PATH: "./build"
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build for Simulator
        script: |
          cd ios
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath "$DERIVED_DATA_PATH"
          cd ..
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/GreetDemoApp.app
