workflows:
  ios-debug-build:
    name: iOS GreetDemoApp (No Signing)
    environment:
      vars:
        XCODE_WORKSPACE: "GreetDemoApp.xcworkspace"
        XCODE_SCHEME: "GreetDemoApp"
      xcode: latest  # or "15.4" if you prefer stability
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build for simulator
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 15'
    artifacts:
      - build/ios/**/*.app
